//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoaySoTrungThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogQuay
    {
        public int ID_LogQuay { get; set; }
        public Nullable<int> CurrentID_Rule { get; set; }
        public Nullable<int> ID_Player { get; set; }
        public Nullable<int> ID_Prize { get; set; }
    }
}
