//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoaySoTrungThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGP
    {
        public int ID_PlayerGP { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Room { get; set; }
        public string BelongType { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Dot { get; set; }
        public Nullable<int> Lan { get; set; }
        public string Giai { get; set; }
    }
}
