//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoaySoTrungThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleToPlay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleToPlay()
        {
            this.Prizes = new HashSet<Prize>();
        }
    
        public int ID_Rule { get; set; }
        public Nullable<int> RoundNumber { get; set; }
        public Nullable<int> PrizeNumber { get; set; }
        public Nullable<int> GuessNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> SoKMDaTrungGiai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prize> Prizes { get; set; }
    }
}
