//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoaySoTrungThuong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class XoaySoTrungThuongEntities : DbContext
    {
        public XoaySoTrungThuongEntities()
            : base("name=XoaySoTrungThuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Prize> Prizes { get; set; }
        public virtual DbSet<RuleToPlay> RuleToPlays { get; set; }
        public virtual DbSet<LogQuay> LogQuays { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerGP> PlayerGPs { get; set; }
        public virtual DbSet<PlayerIV> PlayerIVs { get; set; }
        public virtual DbSet<HinhNen> HinhNens { get; set; }
    
        public virtual ObjectResult<getAllPlayer_Result> getAllPlayer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPlayer_Result>("getAllPlayer");
        }
    
        public virtual int deleteAllPlayer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteAllPlayer");
        }
    
        public virtual int deleteAllGuess()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteAllGuess");
        }
    
        public virtual ObjectResult<GetAllRule_Result> GetAllRule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllRule_Result>("GetAllRule");
        }
    
        public virtual int updateRuleToPlay(Nullable<int> iD_Rule, Nullable<int> roundNumber, Nullable<int> prizeNumber, Nullable<int> guessNumber)
        {
            var iD_RuleParameter = iD_Rule.HasValue ?
                new ObjectParameter("ID_Rule", iD_Rule) :
                new ObjectParameter("ID_Rule", typeof(int));
    
            var roundNumberParameter = roundNumber.HasValue ?
                new ObjectParameter("RoundNumber", roundNumber) :
                new ObjectParameter("RoundNumber", typeof(int));
    
            var prizeNumberParameter = prizeNumber.HasValue ?
                new ObjectParameter("PrizeNumber", prizeNumber) :
                new ObjectParameter("PrizeNumber", typeof(int));
    
            var guessNumberParameter = guessNumber.HasValue ?
                new ObjectParameter("GuessNumber", guessNumber) :
                new ObjectParameter("GuessNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRuleToPlay", iD_RuleParameter, roundNumberParameter, prizeNumberParameter, guessNumberParameter);
        }
    
        public virtual int deleteRuleToPlay(Nullable<int> iD_Rule)
        {
            var iD_RuleParameter = iD_Rule.HasValue ?
                new ObjectParameter("ID_Rule", iD_Rule) :
                new ObjectParameter("ID_Rule", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRuleToPlay", iD_RuleParameter);
        }
    
        public virtual ObjectResult<getAllPrize_Result> getAllPrize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPrize_Result>("getAllPrize");
        }
    
        public virtual int insertPrize(string coCauGiai, string chiTietGiai, Nullable<int> number, string ghiChu, string hinhAnh, Nullable<int> iD_Rule)
        {
            var coCauGiaiParameter = coCauGiai != null ?
                new ObjectParameter("CoCauGiai", coCauGiai) :
                new ObjectParameter("CoCauGiai", typeof(string));
    
            var chiTietGiaiParameter = chiTietGiai != null ?
                new ObjectParameter("ChiTietGiai", chiTietGiai) :
                new ObjectParameter("ChiTietGiai", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var iD_RuleParameter = iD_Rule.HasValue ?
                new ObjectParameter("ID_Rule", iD_Rule) :
                new ObjectParameter("ID_Rule", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertPrize", coCauGiaiParameter, chiTietGiaiParameter, numberParameter, ghiChuParameter, hinhAnhParameter, iD_RuleParameter);
        }
    
        public virtual int deletePrize(Nullable<int> iD_Prize)
        {
            var iD_PrizeParameter = iD_Prize.HasValue ?
                new ObjectParameter("ID_Prize", iD_Prize) :
                new ObjectParameter("ID_Prize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePrize", iD_PrizeParameter);
        }
    
        public virtual int insertLogQuay(Nullable<int> currentID_Rule, Nullable<int> iD_Player, Nullable<int> iD_Prize)
        {
            var currentID_RuleParameter = currentID_Rule.HasValue ?
                new ObjectParameter("CurrentID_Rule", currentID_Rule) :
                new ObjectParameter("CurrentID_Rule", typeof(int));
    
            var iD_PlayerParameter = iD_Player.HasValue ?
                new ObjectParameter("ID_Player", iD_Player) :
                new ObjectParameter("ID_Player", typeof(int));
    
            var iD_PrizeParameter = iD_Prize.HasValue ?
                new ObjectParameter("ID_Prize", iD_Prize) :
                new ObjectParameter("ID_Prize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertLogQuay", currentID_RuleParameter, iD_PlayerParameter, iD_PrizeParameter);
        }
    
        public virtual int updateFlagForPlayer(Nullable<int> iD_Player)
        {
            var iD_PlayerParameter = iD_Player.HasValue ?
                new ObjectParameter("ID_Player", iD_Player) :
                new ObjectParameter("ID_Player", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateFlagForPlayer", iD_PlayerParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CountAllPlayer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountAllPlayer");
        }
    
        public virtual ObjectResult<getAllPlayerGP_Result> getAllPlayerGP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPlayerGP_Result>("getAllPlayerGP");
        }
    
        public virtual ObjectResult<getAllPlayerIV_Result> getAllPlayerIV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPlayerIV_Result>("getAllPlayerIV");
        }
    
        public virtual ObjectResult<Nullable<int>> getDotQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getDotQuay");
        }
    
        public virtual ObjectResult<getGiaiThuong_Result> getGiaiThuong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGiaiThuong_Result>("getGiaiThuong");
        }
    
        public virtual ObjectResult<getLanQuay_Result> getLanQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLanQuay_Result>("getLanQuay");
        }
    
        public virtual ObjectResult<Nullable<int>> getAllDotQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getAllDotQuay");
        }
    
        public virtual ObjectResult<DotQuay_Result> DotQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DotQuay_Result>("DotQuay");
        }
    
        public virtual ObjectResult<Nullable<int>> LanQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LanQuay");
        }
    
        public virtual ObjectResult<string> GiaiThuong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GiaiThuong");
        }
    
        public virtual ObjectResult<PrizeRule_Result> PrizeRule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrizeRule_Result>("PrizeRule");
        }
    
        public virtual ObjectResult<getRuleToPlay_Result> getRuleToPlay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRuleToPlay_Result>("getRuleToPlay");
        }
    
        public virtual ObjectResult<getPrize_Result> getPrize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPrize_Result>("getPrize");
        }
    
        public virtual ObjectResult<getRule_Result> getRule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRule_Result>("getRule");
        }
    
        public virtual ObjectResult<getSoLanDaQuay_Result> getSoLanDaQuay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSoLanDaQuay_Result>("getSoLanDaQuay");
        }
    
        public virtual ObjectResult<getPlayerGP_Result> getPlayerGP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPlayerGP_Result>("getPlayerGP");
        }
    
        public virtual ObjectResult<getPlayerIV_Result> getPlayerIV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPlayerIV_Result>("getPlayerIV");
        }
    
        public virtual int deletePlayerGP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePlayerGP");
        }
    
        public virtual int deletePlayerIV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePlayerIV");
        }
    }
}
